# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
    backend "s3" {
        bucket  = "k8sone"
        key     = "./terraform.tfstate"
        region  = "us-east-2"
        encrypt = true
    }
}
